# -------------------------------
# MapProxy example configuration.
# -------------------------------

# Starts the following services:
# Demo:
#     http://localhost:8080/demo
# WMS:
#     capabilities: http://localhost:8080/service?REQUEST=GetCapabilities&SERVICE=WMS
# WMTS:
#     capabilities: http://localhost:8080/wmts/1.0.0/WMTSCapabilities.xml
#     first tile: http://localhost:8080/wmts/osm/webmercator/0/0/0.png
# Tile service (compatible with OSM/etc.)
#     first tile: http://localhost:8080/tiles/osm/webmercator/0/0/0.png
# TMS:
#     note: TMS is not compatible with OSM/Google Maps/etc.
#     first tile: http://localhost:8080/tms/1.0.0/osm/webmercator/0/0/0.png
# KML:
#     initial doc: http://localhost:8080/kml/osm/webmercator

services:
  demo:
  tms:
    use_grid_names: true
    origin: nw
  kml:
    use_grid_names: true
  wmts:
  wms:
    md:
      title: WMS MapProxy
      abstract: This is a WMS MapProxy

layers:
  - name: osm
    title: OSM
    sources: [osm_cache]

caches:
  osm_cache:
    grids: [webmercator]
    sources: [osm_tms]
    cache:
      type: file
      directory: cache_data/osm

sources:
  osm_tms:
    type: tile
    grid: webmercator
    url: https://tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
    srs: EPSG:3857
    origin: nw

globals:
  cache:
    base_dir: cache_data
    lock_dir: cache_data/locks
    tile_lock_dir: cache_data/tile_locks
    meta_size: [4, 4]
    meta_buffer: 80
  image:
    resampling_method: bicubic
