# ---------------------------------------
# MapProxy seeding configuration.
# ---------------------------------------

seeds:
  myseed1:
    caches: [osm_cache]
    # grids: []
    # coverages: []
    levels:
      to: 10
    refresh_before:
      time: 2013-10-10T12:35:00

cleanups:
  myclean1:
    caches: [osm_cache]
    remove_before:
      days: 14
    levels:
        from: 11

coverages:
